const fs = require('fs');
const path = require('path');

const csvPath = path.join(__dirname, '..', 'src', 'data', 'foodies.csv');
const outPath = path.join(__dirname, '..', 'src', 'data', 'foodies_parsed.js');

function parseRow(line) {
  const fields = [];
  let cur = '';
  let inQuotes = false;
  for (let i = 0; i < line.length; i++) {
    const ch = line[i];
    if (ch === '"') {
      if (inQuotes && line[i+1] === '"') { cur += '"'; i++; continue; }
      inQuotes = !inQuotes;
      continue;
    }
    if (ch === ',' && !inQuotes) {
      fields.push(cur);
      cur = '';
      continue;
    }
    cur += ch;
  }
  fields.push(cur);
  return fields.map(f => f.trim());
}

function toNumOrNull(v) {
  if (v === undefined || v === null) return null;
  if (v === '') return null;
  // some CSV have non-numeric placeholders; try to coerce
  const n = Number(v);
  return isNaN(n) ? v : n;
}

const raw = fs.readFileSync(csvPath, 'utf8');
const lines = raw.split(/\r?\n/).filter(l => l.trim() !== '');
if (lines.length === 0) {
  console.error('CSV empty');
  process.exit(1);
}
const header = parseRow(lines[0]);
const normalizedMap = {
  'Restaurant': 'restaurant',
  'Country': 'country',
  'Menu Item': 'item',
  'URL': 'url',
  'Calories': 'calories',
  'Total Fat (g)': 'totalFat_g',
  'Total Carbs (g)': 'totalCarbs_g',
  'Protein (g)': 'protein_g',
  'Saturated Fat (g)': 'saturatedFat_g',
  'Trans Fat (g)': 'transFat_g',
  'Cholesterol (mg)': 'cholesterol_mg',
  'Sodium (mg)': 'sodium_mg',
  'Dietary Fiber (g)': 'dietaryFiber_g',
  'Sugars (g)': 'sugars_g',
  'Vitamin A (μg)': 'vitaminA_ug',
  'Vitamin C (μg)': 'vitaminC_ug',
  'Calcium (mg)': 'calcium_mg',
  'Iron (mg)': 'iron_mg',
  'Added Sugars (g)': 'addedSugars_g',
  'Vitamin D (μg)': 'vitaminD_ug',
  'Potassium (mg)': 'potassium_mg',
  'Polyunsaturated Fat (g)': 'polyunsat_fat_g',
  'Monounsaturated Fat (g)': 'monounsat_fat_g'
};

const keys = header.map(h => normalizedMap[h] || h);

const rows = [];
for (let i = 1; i < lines.length; i++) {
  const cols = parseRow(lines[i]);
  if (cols.length === 0) continue;
  const obj = {};
  for (let j = 0; j < keys.length; j++) {
    const key = keys[j];
    const val = cols[j] === undefined ? '' : cols[j];
    if (key === 'restaurant' || key === 'country' || key === 'item' || key === 'url') {
      obj[key] = val === '' ? null : val;
    } else {
      obj[key] = toNumOrNull(val);
    }
  }
  // skip empty rows (where restaurant and item are blank)
  if (!obj.restaurant && !obj.item) continue;
  rows.push(obj);
}

// stringify rows to JS file
const outLines = [];
outLines.push('// Parsed from src/data/foodies.csv');
outLines.push('// Auto-generated by scripts/parse_foodies.js');
outLines.push('const foodies = ' + JSON.stringify(rows, null, 2) + ';');
outLines.push('');
outLines.push('export default foodies;');

fs.writeFileSync(outPath, outLines.join('\n'));
console.log('Wrote', outPath, 'with', rows.length, 'entries');
